const projects = [
  {
    title: "EZ Spine",
    about: "A spine classification model using geometric features.",
    motivation: "To automate diagnosis of spinal conditions from X-ray data.",
    languages: "Python",
    libraries: "NumPy, Matplotlib, Scikit-learn",
    skills: "Classification, Feature Engineering, Data Visualization",
    type: "github",
    link: "https://github.com/smante2121/EZ-Spine",
  },
  {
    title: "EZ Spine",
    about: "A spine classification model using geometric features.",
    motivation: "To automate diagnosis of spinal conditions from X-ray data.",
    languages: "Python",
    libraries: "NumPy, Matplotlib, Scikit-learn",
    skills: "Classification, Feature Engineering, Data Visualization",
    type: "github",
    link: "https://github.com/smante2121/EZ-Spine",
  },
  {
    title: "EZ Spine",
    about: "A spine classification model using geometric features.",
    motivation: "To automate diagnosis of spinal conditions from X-ray data.",
    languages: "Python",
    libraries: "NumPy, Matplotlib, Scikit-learn",
    skills: "Classification, Feature Engineering, Data Visualization",
    type: "github",
    link: "https://github.com/smante2121/EZ-Spine",
  },
  {
    title: "EZ Spine",
    about: "A spine classification model using geometric features.",
    motivation: "To automate diagnosis of spinal conditions from X-ray data.",
    languages: "Python",
    libraries: "NumPy, Matplotlib, Scikit-learn",
    skills: "Classification, Feature Engineering, Data Visualization",
    type: "github",
    link: "https://github.com/smante2121/EZ-Spine",
  },
  {
    title: "EZ Spine",
    about: "A spine classification model using geometric features.",
    motivation: "To automate diagnosis of spinal conditions from X-ray data.",
    languages: "Python",
    libraries: "NumPy, Matplotlib, Scikit-learn",
    skills: "Classification, Feature Engineering, Data Visualization",
    type: "github",
    link: "https://github.com/smante2121/EZ-Spine",
  },
  {
    title: "EZ Spine",
    about: "A spine classification model using geometric features.",
    motivation: "To automate diagnosis of spinal conditions from X-ray data.",
    languages: "Python",
    libraries: "NumPy, Matplotlib, Scikit-learn",
    skills: "Classification, Feature Engineering, Data Visualization",
    type: "github",
    link: "https://github.com/smante2121/EZ-Spine",
  },
  {
    title: "EZ Spine",
    about: "A spine classification model using geometric features.",
    motivation: "To automate diagnosis of spinal conditions from X-ray data.",
    languages: "Python",
    libraries: "NumPy, Matplotlib, Scikit-learn",
    skills: "Classification, Feature Engineering, Data Visualization",
    type: "github",
    link: "https://github.com/smante2121/EZ-Spine",
  },
  {
    title: "EZ Spine",
    about: "A spine classification model using geometric features.",
    motivation: "To automate diagnosis of spinal conditions from X-ray data.",
    languages: "Python",
    libraries: "NumPy, Matplotlib, Scikit-learn",
    skills: "Classification, Feature Engineering, Data Visualization",
    type: "github",
    link: "https://github.com/smante2121/EZ-Spine",
  },
];

export default projects;
